name: Pull Request CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Git Checkout
        uses: actions/checkout@v2.0.0

      - name: Install
        working-directory: ./server
        run: npm install
      - name: Build
        working-directory: ./server
        run: npm run build:prod
