name: Pull Request CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install
        working-directory: ./server
        run: npm install
      - name: Build
        working-directory: ./server
        run: npm run build:prd
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install
        working-directory: ./client
        run: npm install
      - name: Build
        working-directory: ./client
        run: npm run build
