name: Pull Request CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node 10.x
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    - name: Git Checkout
      uses: actions/checkout@v2.0.0

    - name: Install
      working-directory: $GITHUB_WORKSPACE/server
      run: npm install
    - name: Build
      working-directory: $GITHUB_WORKSPACE/server
      run: npm run build:prod
